export default {
  USER_LOGIN: "USER_LOGIN",
  VERIFY_TOKEN: "VERIFY_TOKEN",

  USER_REGISTRATION: "USER_REGISTRATION",

  FETCH_ALL_USER: "LOAD_ALL_USER",
  FETCH_USER_BY_ID: "FETCH_USER_BY_ID",
  FETCH_ALL_SECTIONS: "FETCH_ALL_SECTIONS",
  FETCH_SECTION_BY_ID: "FETCH_SECTION_BY_ID",
  FETCH_SECTIONS_LIST: "FETCH_SECTIONS_LIST",
  FETCH_DIVISIONS: "FETCH_DIVISIONS",
  FETCH_DIVISION_BY_ID: "FETCH_DIVISION_BY_ID",
  FETCH_DOCUMENT_TYPES: "FETCH_DOCUMENT_TYPES",
  FETCH_DOCUMENT_TYPE_BY_ID: "FETCH_DOCUMENT_TYPE_BY_ID",
  FETCH_SYSTEM_CURRENT_USER: "FETCH_SYSTEM_CURRENT_USER",
  FETCH_DOCUMENT_BY_ID: "FETCH_DOCUMENT_BY_ID",
  FETCH_DOCUMENT_ACTION_REQUIRED: "FETCH_DOCUMENT_ACTION_REQUIRED",
  FETCH_DOCUMENT_ID: "FETCH_DOCUMENT_ID",
  FETCH_INTERNAL_DESTINATION: "FETCH_INTERNAL_DESTINATION",
  LOAD_USER_BY_SECTION: "LOAD_USER_BY_SECTION",

  ADD_USER: "ADD_USER",
  ADD_DIVISION: "ADD_DIVISION",
  ADD_SECTION: "ADD_SECTION",
  ADD_DOCUMENT_TYPE: "ADD_DOCUMENT_TYPE",
  ADD_DOCUMENT: "ADD_DOCUMENT",
  ADD_DOCUMENT_INPUT_CHANGE: "ADD_DOCUMENT_INPUT_CHANGE",
  ADD_DOCUMENT_ACTION_REQ: "ADD_DOCUMENT_ACTION_REQ",
  ADD_DOCUMENT_DESTINATION: "ADD_DOCUMENT_DESTINATION",
  ADD_DOCUMENT_CREATOR: "ADD_DOCUMENT_CREATOR",
  ADD_DOCUMENT_DRAFT: "ADD_DOCUMENT_DRAFT",

  HANDLE_ONCHANGE_ACTION_REQ: "HANDLE_ONCHANGE_ACTION_REQ",
  VERIFY_USER: "VERIFY_USER",
  USER_PROFILE: "USER_PROFILE",

  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  UPDATE_USERS_LIST: "UPDATE_USERS_LIST",
  UPDATE_DIVISION: "UPDATE_DIVISION",
  UPDATE_SECTION: "UPDATE_SECTION",
  UPDATE_DOCUMENT_TYPE: "UPDATE_DOCUMENT_TYPE",

  DELETE_USER: "DELETE_USER",
  DELETE_DIVISION: "DELETE_DIVISION",
  DELETE_SECTION: "DELETE_SECTION",
  DELETE_DOCUMENT_TYPE: "DELETE_DOCUMENT_TYPE",
  POP_USER: "POP_USER",

  REMOVE_DOCUMENT_ACTION_REQ: "REMOVE_DOCUMENT_ACTION_REQ",
  REMOVE_DESTINATION: "REMOVE_DESTINATION",

  CLEAR_DESTINATION: "CLEAR_DESTINATION",
  CLEAR_EXTERNAL_DESTINATION_INPUT: "CLEAR_EXTERNAL_DESTINATION_INPUT",
  CLEAR_INTERNAL_DESTINATION_INPUT: "CLEAR_INTERNAL_DESTINATION_INPUT",
  CLEAR_ADD_NEW_DOCUMENT_STATE: "CLEAR_ADD_NEW_DOCUMENT_STATE",

  INPUT_CHANGE: "INPUT_CHANGE",
  ONCHANGE_DOCUMENT_TRACKING_NUMBER: "ONCHANGE_DOCUMENT_TRACKING_NUMBER",
  LOG_OUT: "LOG_OUT",

  RECEIVE_DOCUMENT: "RECEIVE_DOCUMENT",
  ACTION_REQ: "ACTION_REQ",
  HANDLE_SCAN: "HANDLE_SCAN"
};
