export default {
  USER_LOGIN: "USER_LOGIN",

  FETCH_ALL_USER: "LOAD_ALL_USER",
  FETCH_USER_BY_ID: "FETCH_USER_BY_ID",
  FETCH_ALL_SECTIONS: "FETCH_ALL_SECTIONS",
  FETCH_SECTION_BY_ID: "FETCH_SECTION_BY_ID",
  FETCH_SECTIONS_LIST: "FETCH_SECTIONS_LIST",
  FETCH_DIVISIONS: "FETCH_DIVISIONS",
  FETCH_DIVISION_BY_ID: "FETCH_DIVISION_BY_ID",
  FETCH_DOCUMENT_TYPES: "FETCH_DOCUMENT_TYPES",
  FETCH_DOCUMENT_TYPE_BY_ID: "FETCH_DOCUMENT_TYPE_BY_ID",

  LOAD_USER_BY_SECTION: "LOAD_USER_BY_SECTION",

  ADD_USER: "ADD_USER",
  ADD_DIVISION: "ADD_DIVISION",
  ADD_SECTION: "ADD_SECTION",
  ADD_DOCUMENT_TYPE: "ADD_DOCUMENT_TYPE",

  VERIFY_USER: "VERIFY_USER",
  USER_PROFILE: "USER_PROFILE",

  UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
  UPDATE_USERS_LIST: "UPDATE_USERS_LIST",
  UPDATE_DIVISION: "UPDATE_DIVISION",
  UPDATE_SECTION: "UPDATE_SECTION",
  UPDATE_DOCUMENT_TYPE: "UPDATE_DOCUMENT_TYPE",

  DELETE_USER: "DELETE_USER",
  DELETE_DIVISION: "DELETE_DIVISION",
  DELETE_SECTION: "DELETE_SECTION",
  DELETE_DOCUMENT_TYPE: "DELETE_DOCUMENT_TYPE",
  POP_USER: "POP_USER",

  INPUT_CHANGE: "INPUT_CHANGE",
  LOG_OUT: "LOG_OUT"
};
