export default {
    ADD_USER: "ADD_USER",
    USER_LOGIN : "USER_LOGIN",
    VERIFY_USER: "VERIFY_USER",
    USER_PROFILE: "USER_PROFILE",
    FETCH_ALL_USER: "LOAD_ALL_USER",
    LOAD_USER_BY_SECTION: "LOAD_USER_BY_SECTION",
    UPDATE_USER_PROFILE: "UPDATE_USER_PROFILE",
    FETCH_USER_BY_ID: "FETCH_USER_BY_ID",
    FETCH_ALL_SECTIONS: "FETCH_ALL_SECTIONS",
    DELETE_USER: "DELETE_USER"
}